### ISSUE TITLE
Example for `KMarkovUpdater` does not work

### ISSUE THREAD

**Issue by a-yildiz** [JuliaPOMDP/BeliefUpdaters.jl#28]
The example provided in the docstring of `KMarkovUpdater` in `src/k_previous_observations.jl` does not work for:
 `pomdp = TigerPOMDP(); policy = solve(QMDPSolver(), pomdp); rng = MersenneTwister();`.

The function `simulate` fails due to `DimensionMismatch`.

**Comment by zsunberg** [comment]
QMDP can't easily be used with a KMarkovUpdater because it requires the belief to be a probability distribution. the dimension mismatch likely occurs because it is trying to interpret the vector of observations as a belief vector.

I think the error message could be improved though - if you'd like to take a stab at that, please create a PR in POMDPPolicies.jl

**Comment by a-yildiz** [comment]
I see, are you able to provide me a working `solver` definition as an example? It's still not 100% clear to me of what is expected as the input. Thanks!

**Comment by zsunberg** [comment]
Hi @a-yildiz , sorry for the delay! I don't think any POMDP solvers are designed to work off the shelf with this updater. More commonly, the KMarkovUpdater is designed to turn a POMDP into an MDP when the state can be described with sufficient fidelity by the last k observations. For example I think the DeepQLearning module does this. You could create a belief MDP with:
```
using POMDPModelTools: GenerativeBeliefMDP

bmdp = GenerativeBeleifMDP(pomdp, KMarkovUpdater(4))
```

(see https://juliapomdp.github.io/POMDPModelTools.jl/stable/model_transformations/#POMDPModelTools.GenerativeBeliefMDP for docs)
